# GitHub Pages workflow for Jekyll site
name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # or your desired Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy
        uses: actions/deploy-pages@v4
