<<<<<<< HEAD
name: Build and Deploy Jekyll Site to GitHub Pages
=======
# GitHub Pages workflow for Jekyll site
name: Deploy Jekyll Site to GitHub Pages
>>>>>>> seo/gh-pages-workflow

on:
  push:
    branches:
<<<<<<< HEAD
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
=======
      - main  # Set a branch to deploy

jobs:
  jekyll:
>>>>>>> seo/gh-pages-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
<<<<<<< HEAD
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
=======
          ruby-version: '3.2' # or your desired Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy
>>>>>>> seo/gh-pages-workflow
        uses: actions/deploy-pages@v4
